name: 'Check formatting'
description: 'Check the formatting of every .scala file if any has changed'


inputs:
  force:
    default: 'false'
    required: false
    description: 'If set to true, the Get changed files step will be ignored'

runs:
  using: "composite"
  steps:
    - name: Check repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      if: inputs.force == 'false'
      uses: tj-actions/changed-files@v38
      with:
        files: '**/*.scala'

    - name: Check formatting
      if: |
        inputs.force == 'true' ||
        steps.changed-files.outputs.all_changed_and_modified_files_count > 0
      uses: ./.github/actions/sbt
      with:
        command: scalafmtCheckAll
