name: 'SBT build'
description: 'Setup and run a SBT build'

inputs:
  command:
    description: 'SBT command(s) to run'
    required: true
  java-version:
    description: 'Java version'
    required: true
    default: 19
  java-distribution:
    description: 'Java distribution'
    required: true
    default: zulu
  background:
    description: 'Fork in background'
    required: true
    default: false

runs:
  using: "composite"
  steps:

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        cache: sbt

    - name: Restore cache
      uses: actions/cache/restore@v3
      with:
        path: |
          ${{ github.workspace }}/**/target
          ~/.ivy2/local
          ~/.cache/scalablytyped
        key: build-${{ github.ref }}-${{ github.run_id }}
        restore-keys: |
          build-${{ github.ref }}
          build-

    - name: Run sbt
      shell: bash
      run: sbt -v "${{ inputs.command }}" ${{ inputs.background == 'true' && '&' || '' }}

    - name: Save cache
      uses: actions/cache/save@v3
      with:
        path: |
          ${{ github.workspace }}/**/target
          ~/.ivy2/local
          ~/.cache/scalablytyped
        key: build-${{ github.ref }}-${{ github.run_id }}
