package cleareth.model

import cleareth.model.constraint.IsHexWordStrict
import io.github.iltotore.iron.*
import scodec.bits.ByteVector

opaque type Byte1  = ByteVector :| IsHexWordStrict[1]
opaque type Byte2  = ByteVector :| IsHexWordStrict[2]
opaque type Byte3  = ByteVector :| IsHexWordStrict[3]
opaque type Byte4  = ByteVector :| IsHexWordStrict[4]
opaque type Byte5  = ByteVector :| IsHexWordStrict[5]
opaque type Byte6  = ByteVector :| IsHexWordStrict[6]
opaque type Byte7  = ByteVector :| IsHexWordStrict[7]
opaque type Byte8  = ByteVector :| IsHexWordStrict[8]
opaque type Byte9  = ByteVector :| IsHexWordStrict[9]
opaque type Byte10 = ByteVector :| IsHexWordStrict[10]
opaque type Byte11 = ByteVector :| IsHexWordStrict[11]
opaque type Byte12 = ByteVector :| IsHexWordStrict[12]
opaque type Byte13 = ByteVector :| IsHexWordStrict[13]
opaque type Byte14 = ByteVector :| IsHexWordStrict[14]
opaque type Byte15 = ByteVector :| IsHexWordStrict[15]
opaque type Byte16 = ByteVector :| IsHexWordStrict[16]
opaque type Byte17 = ByteVector :| IsHexWordStrict[17]
opaque type Byte18 = ByteVector :| IsHexWordStrict[18]
opaque type Byte19 = ByteVector :| IsHexWordStrict[19]
opaque type Byte20 = ByteVector :| IsHexWordStrict[20]
opaque type Byte21 = ByteVector :| IsHexWordStrict[21]
opaque type Byte22 = ByteVector :| IsHexWordStrict[22]
opaque type Byte23 = ByteVector :| IsHexWordStrict[23]
opaque type Byte24 = ByteVector :| IsHexWordStrict[24]
opaque type Byte25 = ByteVector :| IsHexWordStrict[25]
opaque type Byte26 = ByteVector :| IsHexWordStrict[26]
opaque type Byte27 = ByteVector :| IsHexWordStrict[27]
opaque type Byte28 = ByteVector :| IsHexWordStrict[28]
opaque type Byte29 = ByteVector :| IsHexWordStrict[29]
opaque type Byte30 = ByteVector :| IsHexWordStrict[30]
opaque type Byte31 = ByteVector :| IsHexWordStrict[31]
opaque type Byte32 = ByteVector :| IsHexWordStrict[32]

object Byte1  extends IsHexWordStrict.Utils[1, Byte1]
object Byte2  extends IsHexWordStrict.Utils[2, Byte2]
object Byte3  extends IsHexWordStrict.Utils[3, Byte3]
object Byte4  extends IsHexWordStrict.Utils[4, Byte4]
object Byte5  extends IsHexWordStrict.Utils[5, Byte5]
object Byte6  extends IsHexWordStrict.Utils[6, Byte6]
object Byte7  extends IsHexWordStrict.Utils[7, Byte7]
object Byte8  extends IsHexWordStrict.Utils[8, Byte8]
object Byte9  extends IsHexWordStrict.Utils[9, Byte9]
object Byte10 extends IsHexWordStrict.Utils[10, Byte10]
object Byte11 extends IsHexWordStrict.Utils[11, Byte11]
object Byte12 extends IsHexWordStrict.Utils[12, Byte12]
object Byte13 extends IsHexWordStrict.Utils[13, Byte13]
object Byte14 extends IsHexWordStrict.Utils[14, Byte14]
object Byte15 extends IsHexWordStrict.Utils[15, Byte15]
object Byte16 extends IsHexWordStrict.Utils[16, Byte16]
object Byte17 extends IsHexWordStrict.Utils[17, Byte17]
object Byte18 extends IsHexWordStrict.Utils[18, Byte18]
object Byte19 extends IsHexWordStrict.Utils[19, Byte19]
object Byte20 extends IsHexWordStrict.Utils[20, Byte20]
object Byte21 extends IsHexWordStrict.Utils[21, Byte21]
object Byte22 extends IsHexWordStrict.Utils[22, Byte22]
object Byte23 extends IsHexWordStrict.Utils[23, Byte23]
object Byte24 extends IsHexWordStrict.Utils[24, Byte24]
object Byte25 extends IsHexWordStrict.Utils[25, Byte25]
object Byte26 extends IsHexWordStrict.Utils[26, Byte26]
object Byte27 extends IsHexWordStrict.Utils[27, Byte27]
object Byte28 extends IsHexWordStrict.Utils[28, Byte28]
object Byte29 extends IsHexWordStrict.Utils[29, Byte29]
object Byte30 extends IsHexWordStrict.Utils[30, Byte30]
object Byte31 extends IsHexWordStrict.Utils[31, Byte31]
object Byte32 extends IsHexWordStrict.Utils[32, Byte32]
