name: build

on:
  push:
    branches:
      - main
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

concurrency:
  group: CI-${{ github.ref }}
  cancel-in-progress: true

jobs:

  check-formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check-formatting

  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: [ evm-codec ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/sbt
        with:
          command: ${{ matrix.component }}/Test/test
