name: release

on:
  push:
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}

jobs:
  docker-publish:
    name: publish-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            .ivy2
            .sbt
          key: cleareth-cache-${{ hashFiles('build.sbt', 'Dependencies.scala', 'plugins.sbt') }}
          restore-keys: |
            cleareth-cache-${{ hashFiles('build.sbt', 'Dependencies.scala', 'plugins.sbt') }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CI_BOT_USERNAME }}
          password: ${{ secrets.CI_BOT_TOKEN }}
      - name: Build ${{ matrix.component }}
        run: sbt "${{ matrix.component }}/docker:publish"
